### ISSUE TITLE
Error when trying the merge value from user_profile_data

### ISSUE THREAD

**Issue by jaypha** [jpahullo/moodle-tool_mergeusers#239]
Hi.
When trying this plugin I came across a problem where values from the 'user to be removed' was not being transferred to 'user to be kept'.

**Steps to reproduce:**

Set up a vanilla Modole 4.0 with 'master' branch (d7121e963) of merge users installed.
Create a text user profile field. Give it a suitable name (say, 'Dent').
In merge users settings, for 'Exclude exceptions' setting, have 'user_info_data' selected.

Create an account via 'new user'. Set 'Dent' to a suitable value.

Create another account. Leave 'Dent' blank.

Confirm that the first account has a value set for 'Dent', but is empty for the second.

Go to merge users. Select the two accounts for merging, the first one to be removed, the second one to be kept.

Do the merge.

Confirm in the logs that a DELETE for user_info_data happened, but not an UPDATE for user_info_data. (There may be logs for other tables).

Check the user accounts and confirm that the value of the profile field has not been successfully transferred.

**Investigation**

I investigated the code and found the likely cause within the GenericTableMerger::updateRecords().

The method tries to update the table, but fails because of the uniqueness constraint. It then does a delete, but does not make a second attempt to update.

Regards

**Comment by jpahullo** [comment]
Hi @jaypha,

Thanks for reporting.

Reading your report, it is the expected behaviour. A suitable record exists for both users (no matter what value appears on them), so it, as expected, tries the best. So, due to the constraint, it just deletes the record from the user to remove.

It is difficult to consider that this operation should be performed as you state:

1. Which is the "current" value for the person?
2. The data from the user to remove? Or is it stale?
3. Or should be considered the data from the user to keep? Or is it stale?

From the process, and from the context, it is difficult to decide beforehand which value to keep.

And, with all respect, I consider that "empty/blank" values should not be considered as "no record", since maybe the current data for the user is just "no data".

If you construct something about this that may have sense, maybe with extra plugin settings and extra processing on the merge operation, share here on another issue.

By now, I am closing this issue.

Thanks for reporting,

Jordi
