### ISSUE TITLE
2 issue

### ISSUE THREAD

**Issue by LeeTV1** [jpahullo/moodle-tool_mergeusers#262]
When opening the merge tool (log or to merge), we get this error: 
Version 4.2.5

Warning: include(): Failed opening '/home/hcta_lms/learn/moodle/lib/editor/tinymce/version.php' for inclusion (include_path='/home/hcta_lms/learn/moodle/lib/pear:.:') in /home/hcta_lms/learn/moodle/lib/classes/plugin_manager.php on line 308

Deprecated: Creation of dynamic property AssignSubmissionTableMerger::$duplicateddatamerger is deprecated in /home/hcta_lms/learn/moodle/admin/tool/mergeusers/lib/table/assignsubmissiontablemerger.php on line 34
[Skip to main content](https://learn.healthcaretrainingacademy.org/admin/tool/mergeusers/index.php?#maincontent)

**Comment by jpahullo** [comment]
Hi @LeeTV1 ,

Thanks for the feedback. 

The first "Warning: include():" is about your installation. It seems like you have a missing plugin there. 

The second "Deprecated: Creation of dynamic property" is related to the PHP version you are using. Please, could you provide the PHP version?

However, it is not a problem using it still. You see these messages becuase you have a debugging level like developer or so on Moodle. If you set this debugging level up to production, you will not see these notices.

Thanks,

Jordi

**Comment by LeeTV1** [comment]
Hi Jordi:

Thank you for replying. Our PHP is 8.2. I’m not a programmer, but I understand that various functions were deprecated. 

Do you have any inclination as to why we may be missing a plugin (and if so, which one)?

Thank you again

Lee

**Comment by jpahullo** [comment]
Hi @LeeTV1 ,

Contact with your system administrator or similar role and send them these warnings, they will know what to do for sure.

Just in case it may help:
1.  the first warning is about a missing tinymce editor plugin. Could it be present in some previously on this Moodle installation? It is not related to this plugin.
2. The warning related to this plugin, that about "Deprecated: Creation of dynamic property" is related to your PHP 8.2 version. It is safe to use it and it will not incur in any trouble. I will create a new issue to review this plugin against PHP 8.2 and try to solve any deprecation warning and anything else related to PHP version. I can see that since Moodle 4.2.3 we can use PHP 8.2, so this is good to consider.

I am closing it right now for the above reasoning.

Thanks for the feedback. 

Jordi
