### ISSUE TITLE
Problme when merging

### ISSUE THREAD

**Issue by EsdrasCaleb** [jpahullo/moodle-tool_mergeusers#264]
After updating the plug-in i am stuck in this screen when I try merge users
![Captura de tela de 2024-02-26 12-35-06](https://github.com/jpahullo/moodle-tool_mergeusers/assets/1126400/85c73d87-6388-44df-b016-6c8d90266813)

**Comment by jpahullo** [comment]
Hi  @EsdrasCaleb,

I have never seen something similar over there. I can assume it is something related to your plugin subcourse, and not related to this plugin.

You see it because you have DEVELOPER debug. If you put it in production debug (no debug), it all will operate normally.

But in summary, it should work properly even seeing these notices. I will leave this open to check that warning if I have time.

Please, provide:

1. PHP version
2. Moodle version
3. subcourse version

Thanks for the feedback.

**Comment by EsdrasCaleb** [comment]
You are rigth. removing debug it works flawless. Thx
