### ISSUE TITLE
sql views should be ignored 

### ISSUE THREAD

**Issue by danbuntu** [jpahullo/moodle-tool_mergeusers#266]
I've just tried to merge a user of one of my sites. The site also has several SQL on it that are used for reporting purposes.

It appears that because the views contain the column userid the merge users tools thought it needed to make a change to them. It failed because you can't update a view like this.

It would be nice if the tool could automatically skip views.

**Comment by jpahullo** [comment]
Thanks for the feedback.

I agree with you. Could you provide a patch for it? It would be quicker to integrate.

Thanks,

Jordi

**Comment by jpahullo** [comment]
By de way, @danbuntu:

We also have views in our production site, and what we always did is to use a different prefix. There is no problem using them inside Moodle thouth: instead of using them like `{viewname}`, you can do like `v_viewname` inside your SQLs.

Maybe you can consider this meanwhile this is not solved into the plugin.

One more generic way, maybe, it could be providing a list of tables to omit from iterating through into the plugin. But it may be really dangerous if it is used badly. It would be neater if the plugin directly list all tables, excluding views. I do not know if this would also apply to materialized views. This is way I considered also a simple list of tables to not be processed by this plugin.

Thanks,

Jordi

**Comment by danbuntu** [comment]
Hello thank you for getting back to me. I've taken a look at the code this morning and it's revealed two things.
The first is that you automatically ignore any table/ view that doesn't have the $CFG->prefix in front if it. My views did start zz_ - unfortunately they also started mdl_ - ie. mdl_zz_viewname. When I renamed them to just zz_ everything started to work fine, so problem sorted. Attached is a README patch for consideration- although let’s be honest I probably wouldn’t have read this 😊

Secondly I took a look automatically ignoring the views. Unfortunately, the core Moodle get_tables function literally only returns the table names – there is also a different version of the function based on DB server type. So the only way I could see to do it would be to either clone the various functions and alter each one to return the table/ view flag. Alternatively, as you loop the table names you would need to test each one – this would likely be slow and a bit of a headache to maintain. I think the documentation change might be the best fix.

Bonus third thing. I’ve never come across seen the way you do the screen switching before with a case to switch between rendering the various stages of the form. So I’ve learnt something cool as well.

[Update_README_to_include_information_about_views.patch](https://github.com/jpahullo/moodle-tool_mergeusers/files/15073860/Update_README_to_include_information_about_views.patch)

**Comment by jpahullo** [comment]
Thank you for your effort and feedback.

I will consider the patch to the README file. Thank you! Thank you also for sharing your learning experience, hehe.

Your reasoning (no natural way of knowing if it is a view or table inside Moodle) is what brought to me to think that a general list of tables from which the admin could select views for preventing processing them.

So, yes, the neatest way to prevent processing views is to define them with a totally different prefix, as you did.

Thanks again,

Jordi
