### ISSUE TITLE
Unnecessary popup on the 'Merge user accounts' page

### ISSUE THREAD

**Issue by dragos5436** [jpahullo/moodle-tool_mergeusers#270]
There appears to have been a recent change on the 'Merge user accounts' page, which is creating some confusion:
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/73345838/ada51174-2429-4b37-89c9-0f2452d9c171)

The ‘Merge user accounts’ button leads to:
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/73345838/debc967f-afa1-4ab7-adfa-dc2703019e7d)

Then the ’Yes’ button leads to:
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/73345838/29b770d3-23a8-47db-b0ed-2fb30d10886d)

At this point ’Cancel’ stops the process and returns to the previous screen.
‘Leave’ continues the merge process.

This last pop-up message seems to be a surplus, can it be removed ?

Thanks

Moodle version 4.3.4
PHP version 8.0

**Comment by jpahullo** [comment]
Hi @dragos5436,

The first two screenshots are from the plugin. However, the last screenshot is someone from the browser, not plugin-specific. Web browser is telling you that you have some form modified and you are leaving that web page without storing the form.

This is the first time I see this with the merging user form. 

Which web browser are you using? Is the third screenshot happening all the times?

Thanks for the feedback.

Jordi

**Comment by dragos5436** [comment]
Hi Jordi,

I have tested this on Chrome, Edge and Firefox. The browser pop-up asking whether you wanna leave the page or not seems to appear on all of them when clicking the 'Yes' button on the 'Confirmation' pop-up in Moodle. And yes, it happens each time we want to merge two user accounts.

Regards,

Dragos

**Comment by jpahullo** [comment]
Ok, thanks for the feedback.

I will check it locally and with my colleagues.

Regards,

Jordi

**Comment by jpahullo** [comment]
Hi, 

I need more details.

I tried this:

1. search for one user and choosing it for user to keep.
2. search for another user and selecting it for user to remove: 
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/2048296/a66781a8-6e73-4117-b669-75b033b5e6a5)
3. press the button to merge users: 
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/2048296/c3003f72-dfde-4dbc-ac75-88de2a01af02)
4. click "yes" on popup message: 
![image](https://github.com/jpahullo/moodle-tool_mergeusers/assets/2048296/65e4f667-2fd2-4393-baa9-cf9e97b8348c)
   * At this point, there is no form on the web page, so browser cannot say that. 
5. No other popup is shown. So I do not see that popup from the browser. 

I also tried the other option looking for user to keep and remove at once.

On Moodle 4.1 and using brave, firefox.

Maybe you have some theme or plugin in your Moodle that introduces some form on that page, and that brings you that last popup from the browser.

So, I am closing it by now, since it is not related to the plugin.

Thanks for contacting.

Jordi
