### ISSUE TITLE
Failure to ignore 'custom' tables

### ISSUE THREAD

**Issue by sprezlaus** [jpahullo/moodle-tool_mergeusers#284]
Not a major issue, but worth mentioning:
Someone decided to backup some tables at a certain point, and we ended up with some copied tables with a '-bu'-suffix.
This lead to the following error:
13281994 Query	SELECT id FROM {**user_info_data -bu**} WHERE userid = '71851' **NB: this is the actual tablename**
		13281994 Query	ROLLBACK
		13281996 Query	SELECT * FROM mdl_registration_hubs WHERE huburl = 'https://stats.moodle.org'
		13281994 Query	INSERT INTO mdl_tool_mergeusers (touserid,fromuserid,timemodified,mergedbyuserid,success,log) VALUES('71852','71851','1730724169','32668','0','[\"Exception thrown when merging: \'Error reading from database\\\".<br \\/>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'-bu}
		
I renamed the table and the error is fixed.
At first I thought it was the hyphen, but after removing that, it seemed that the Exception originated from the space rather than the hyphen.

**Comment by jpahullo** [comment]
Hi @sprezlaus,

Thanks for the feedback.

I think this is not a question about this plugin, but for table naming in general. Maybe that table was a backup named in that way. I do not know why whitespaces were allowed when naming that table that way. I know MariaDB and MySQL variants have a specific syntax with:

``` 
`some_name`
```
or similar, which would allow you to type any value there, but it is not a good practice in general. Names for tables, columns and so on should not contain whitespaces and other special characters, for better compatibility.

We will not address any development to address this, since it is a MariaDB specific issue with allowed naming.

Anyway, thanks a lot for contacting us. It will serve to other users how to proceed in a similar scenario.

Thanks!

Jordi
